### ISSUE TITLE
"ember install:addon" fails with "The specified command install:addon is invalid."

### ISSUE THREAD

**Issue by jerryh-njvc** [sir-dunxalot/ember-easy-form-extensions#22]
Installation instructions say to run this command:
**ember install:addon ember-easy-form-extensions**

I get result **The specified command install:addon is invalid. For available options, see `ember help`.**

I am using ember 1.11.1, Ember-CLI 0.2.3, node 0.12.2, and npm 2.7.6

**Comment by sir-dunxalot** [comment]
@jerryh-njvc Ember CLI's syntax changed with the latest release. You should now use:

```
ember install ember-easy-form-extensions
```

I'll change the wiki right now - thanks!

**Comment by sir-dunxalot** [comment]
[Fixed here](https://github.com/sir-dunxalot/ember-easy-form-extensions/commit/b6c908cf9b668439979164cac75fdb2ab8a2acae)
