### ISSUE TITLE
After install, Ember.Validations is not defined.

### ISSUE THREAD

**Issue by jerryh-njvc** [sir-dunxalot/ember-easy-form-extensions#23]
I am upgrading an ember project, and have replaced handlebars with htmlbars. The addons **ember-easy-form** and **ember-validations** were already installed. I installed **ember-easy-form-extensions** to get over the htmlbars barrier. Per the installation instructions, I removed **ember-easy-form** and **ember-validations**, and then installed **ember-easy-form-extensions**.

This declaration in one of my models...

``` javascript
export default DS.Model.extend( Ember.Validations.Mixin, CreatedByMixin, {
    // my list of attributes
});
```

is throwing this error...
`TypeError: Cannot read property 'Mixin' of undefined`

I am new to ember. How can I test if **ember-validations** was successfully installed and is accessible by my models?

I uninstalled **ember-validations** by removing the line that mentions this addon from `bower.json` and `Brocfile.js`.

**Comment by alexBaizeau** [comment]
You probably were on an older version of ember-validations, the declaration of your model should look like that now

``` javascript
import 'EmberValidations' from 'ember-validations';
export default DS.Model.extend( EmberValidations.Mixin, CreatedByMixin, {
    // my list of attributes
});
```

**Comment by sir-dunxalot** [comment]
I think Alex is correct here. See the [Ember Validations usage instructions](https://github.com/dockyard/ember-validations#usage). If that doesn't fix it then I'll be happy to reopen this issue and look into it.

**Comment by jerryh-njvc** [comment]
Thank you so much @alexBaizeau for your fix. That was it. It only worked for me when EmberValidations was _not_ quoted.

``` javascript
import EmberValidations from 'ember-validations';
export default DS.Model.extend( EmberValidations.Mixin, CreatedByMixin, {
    // my list of attributes
});
```
