### ISSUE TITLE
Error in 1.13.0-beta.2: Cannot read property 'helperFunction' of undefined

### ISSUE THREAD

**Issue by joostdevries** [sir-dunxalot/ember-easy-form-extensions#27]
Just fired up our app on 1.13.0-beta.2 and got the following error when I try to render a template with a form:
![image](https://cloud.githubusercontent.com/assets/3824616/7853949/c9629b92-0514-11e5-99fc-14b8f455c24a.png)

![image](https://cloud.githubusercontent.com/assets/3824616/7853963/eff6a0aa-0514-11e5-9aee-a9be9565dd02.png)

**Comment by sir-dunxalot** [comment]
So I haven't tried this out with `1.13.0-beta` yet but Easy Form has significant difficulties getting past Ember `0.12`. I decided it best to move away from continuing to hack away the vendor file in favor of a real modulized, Ember addon.

Please see [this branch](https://github.com/sir-dunxalot/ember-easy-form-extensions/tree/ember-1.11), which is currently in user testing and supports Ember 1.12. It matches easy form's syntax closely, with the exception of needing dasherized names for helpers, etc, and does all the same stuff (e.g. working out-of-the-box with validations). The only feature currently not supported is translations. You can see the branch's readme for more info.

**Comment by joostdevries** [comment]
@sir-dunxalot looks great. Will try to test it in our app soon. In this branch you've completely removed dockyard's easyform right?

**Comment by sir-dunxalot** [comment]
Correct! It does exactly the same thing but I rewrote it from the ground up for Ember CLI. There's a few people testing it right now, including some of my collegues, so all feedback and suggestions will be very much valued. I know the Dockyard guys are planning on rewriting EasyForm after Ember 2.0 but I hope this will tide us all over in the meantime. Once the branch has significant approval I'll work on testing and will make an official release (maybe in 7-10 days).

**Comment by sir-dunxalot** [comment]
Ember 1.13 support will be guaranteed in the [1.13 branch](https://github.com/sir-dunxalot/ember-easy-form-extensions/tree/1.13), which I expect will be the `1.0` release of this addon. It's a cleaner API, doesn't rely on private Ember methods, and will 'tide us over' until Dockyard rewrites Easy Form. Thus, the `ember-1.11` branch might never see an official release. I'm hoping to have a prerelease up within 7-10 days.

**Comment by sir-dunxalot** [comment]
This will be fixed by #37
