### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by stefanpenner** [sir-dunxalot/ember-easy-form-extensions#28]
https://github.com/ember-cli/ember-cli/issues/4199

**Comment by sir-dunxalot** [comment]
Thank you for the diligence - I will fix and publish with the next release.

Goal: End of Tuesday June 2nd.

**Comment by stefanpenner** [comment]
like: https://github.com/ember-cli/ember-cli/commit/6ac18227ea571988fa9d9950e9a1051fdd990c7c

**Comment by sir-dunxalot** [comment]
Ok, got it :+1:

**Comment by sir-dunxalot** [comment]
Fixed and released. Thanks again.
