### ISSUE TITLE
1.11.0.beta error on {{input-group selection=model.foo content=model.foos}}

### ISSUE THREAD

**Issue by Truffula** [sir-dunxalot/ember-easy-form-extensions#31]
If no `value` is set,  there is no `property` so `cleanProperty` throws an error:

``` js
cleanProperty: Ember.computed('property', 'modelPath', function () {
    return this.get('property').replace(this.get('modelPath'), '');
    // Uncaught TypeError: Cannot read property 'replace' of undefined
}),
```

If both value and selection are passed, it doesn't error, but treats it as a 'value' select; properties such as `optionValuePath` and `optionLabelPath` are not passed on to the `{{view 'select'}}` in `app/templates/form-inputs/select.hbs`.

**Comment by Truffula** [comment]
Quick-n-dirty workaround (using both value and selection):

``` hbs
{{input-group
  selection=model.foo
  value=model.foo
  content=model.foos
  optionValuePath="content.id"
  optionLabelPath="content.title"}}
```

``` hbs
// app/templates/form-inputs/select.hbs
{{view 'select'
  id=inputId
  content=content
  name=name
  selection=selection
  prompt=prompt
  disabled=disabled
  required=required
  invalid=isInvalid
  optionValuePath=optionValuePath
  optionLabelPath=optionLabelPath
}}
```

Edit: Updated `select.hbs`. I discovered that it doesn't matter if you have both `value` and `selection` (`selection` seems to override `value` - the missing `optionValue*` properties were part of that problem).

**Comment by sir-dunxalot** [comment]
Thanks for opening the issue. I'll try and get a release pushed to the beta branch soon.

**Comment by jme783** [comment]
Has this been addressed? I ask because even thought I use `optionLabelPath` and `optionValuePath` in my code, the property on the model is still saved as the entire object used as the `content`

**Comment by sir-dunxalot** [comment]
`{{input-group}}` has been removed as of the `2.0.0` release because Ember EasyForm now has a `1.0.0.rc-1` release for form components.
