### ISSUE TITLE
How can I install 1.0.0.beta prerelease?

### ISSUE THREAD

**Issue by lhwong** [sir-dunxalot/ember-easy-form-extensions#33]
Hi,
I am using Ember 1.12. As given, "Usage with Ember 1.11 and above is compatible with the 1.0.0.beta prerelease - see here."

Using the following command, version 0.2.11 is installed as expected

ember install ember-easy-form-extensions

How can I install version 1.0.0.beta?
I tried by adding the following to package and using npm install
1. "ember-easy-form-extensions": "1.0.0.beta"
Expected as this version is not available at https://registry.npmjs.org
2. "ember-easy-form-extensions": "https://github.com/sir-dunxalot/ember-easy-form-extensions/tree/1.0.0.beta"
Getting
"npm ERR! fetch failed with status code 406"

Kindly advice how can I install the version which is compatible with Ember 1.11 and above.

Regards,
Nick

**Comment by lhwong** [comment]
Found the answer at https://github.com/sir-dunxalot/ember-easy-form-extensions/releases

Regards,
Nick

**Comment by sir-dunxalot** [comment]
I'll make it clearer in the README. Please give any feedback on the API, ease of use, parity with previous Easy Form versions, etc, as I'd like to get everything working as slick as possible before releasing.
