### ISSUE TITLE
How to show group of checkboxes? 

### ISSUE THREAD

**Issue by lhwong** [sir-dunxalot/ember-easy-form-extensions#36]
Dear,

How can I create group of checkboxes like the following?

```
<input type="checkbox" name="animal" value="Cat" />Cats <br />
<input type="checkbox" name="animal" value="Dog" />Dogs<br />
<input type="checkbox" name="animal" value="Bird" />Birds<br />
```

Regards,
--Nick

**Comment by sir-dunxalot** [comment]
Hey Nick,

Are you using the master branch (default npm release) or the ember-1.11 branch?

**Comment by lhwong** [comment]
Hi Duncan,
I am using ember-1.11 branch.

Regards,
--Nick

**Comment by sir-dunxalot** [comment]
So I believe you want to do something like:

```
{{input value='Cat' name='animal' type='checkbox'}}
{{input value='Dog' name='animal' type='checkbox'}}
```

Does that not work? If not my guess would be that the checkbox is expecting `value` to be passed a boolean property. If that's the case, you may need to refactor to something like the following and manually build the animal property.

```
{{input value=isCat type='checkbox'}}
{{input value=isDog type='checkbox'}}
```

Another option is to use the `{{input-group}}` component in block form and use HTML for the checkboxes:

```
{{#input-group value=animal}}
  <input type="checkbox" name="animal" value="Cat" />Cats <br />
  <input type="checkbox" name="animal" value="Dog" />Dogs<br />
  <input type="checkbox" name="animal" value="Bird" />Birds<br />
{{/input-group}}
```

Finally, you might want to ask if this use case better suits radio buttons.

Does that help?

**Comment by lhwong** [comment]
Yes, that helps. Thank you very much.
