### ISSUE TITLE
Adding Bootstrap 3 Classes

### ISSUE THREAD

**Issue by dslamba** [sir-dunxalot/ember-easy-form-extensions#42]
I cannot seem to find a way to add Bootstrap 3 classes to these forms. changing className on inputgroup, does not change the input itself.
There must be a way to templatize this such that a form looks like Bootstrap 3 template?

**Comment by dslamba** [comment]
For now I have used a workaround.
1. Redefine the "label" class for the form. This addon adds this class to form labels but bootstrap labels have different color and font.
2. Add custom input types for each input and add class= property for it.

Ideally, we should add a new property on input-group that passes the class down to the input-field.

**Comment by sir-dunxalot** [comment]
Hi,

What version of this addon and Ember are you using?

**Comment by dslamba** [comment]
I am on 1.0.2 for Easy Form Extensions. On 1.13.5 for Ember.

**Comment by sir-dunxalot** [comment]
With #48 (released as `2.0.0`), form components are no longer a part of this library. Ember EasyForm has a `1.0.0.rc-1` release.
