### ISSUE TITLE
form submission button not displayed after error in Ajax 

### ISSUE THREAD

**Issue by lhwong** [sir-dunxalot/ember-easy-form-extensions#43]
Hi,
In the controller, I make ajax call like the following. Whenever error happens in ajax call such as 500 or 422, the form fields are still displayed on the page but not the form submission buttons (Save and Cancel). I'd like to allow the user to modify the input on the fields and re-submit. Any idea on how to achieve this?

```
export default Ember.Controller.extend(
  Saving, {

save: function() {
 ajax({
          url: ENV.APP.API_HOST + "/api/1/" + route + "?taskId=" + this.model.get('id'),
          method: "POST",
          //dataType: "json",
          contentType: "application/json",
          data: JSON.stringify(member)
      }).then(function(response) { 

          console.log(response);
          that.transitionToRoute('members'); 

      });    
}

}
```

Regards,
Nick

**Comment by sir-dunxalot** [comment]
Hi Nick,

What version of this addon are you using? You can call `this.resetForm()` in newer versions. If that method isn't available, try `this.set('formSubmitted', false)`.

Let me know if that doesn't work.

**Comment by lhwong** [comment]
Hi Ducan,
I am using "ember-easy-form-extensions": "sir-dunxalot/ember-easy-form-extensions#ember-1.11".
this.set('formSubmitted', false) works. 

Thank you very much. 

Regards,
--Nick
