### ISSUE TITLE
InputGroup#setBindingForValue called twice per property, 2nd times doesn't honor modelPath

### ISSUE THREAD

**Issue by walter** [sir-dunxalot/ember-easy-form-extensions#45]
...and the end result is that the value binding doesn't point at the expect object's properties.

This is with ember-cli 1.13.8, ember 1.13.7, and ember-data 1.13.8. The `form-controls` call doesn't specify modelPath and therefore it should be 'model'.

For my own work, I've put in a hardcoded workaround in a fork. The changes are in this commit, along with console logging to confirm that the setBindingForValue was happening twice per property and the 2nd time was not specifying the full path:

https://github.com/walter/ember-easy-form-extensions/commit/c97c24ea0b15b82d15850a6eacf0b161e42f0df5

**Comment by sir-dunxalot** [comment]
Thanks for the example in the fork! I'll look into this as soon as I can.

**Comment by sir-dunxalot** [comment]
`{{input-group}}` was removed with #48 (released as `2.0.0`). I recommend trying Ember EasyForm's `1.0.0.rc-1` release, which came out recently.
