### ISSUE TITLE
Cannot set property 'formForModelPath' of undefined

### ISSUE THREAD

**Issue by tspacek** [sir-dunxalot/ember-easy-form-extensions#9]
Using Ember 1.10, handlebars 2.0.0 and ember-cli-htmlbars 0.7.4 I get:

`TypeError: Cannot set property 'formForModelPath' of undefined`

From

```
Ember.Handlebars.registerHelper('form-for', function(object, options) {
  options.data.keywords.formForModelPath = object;
  return EasyFormShims.viewHelper(this, Ember.EasyForm.Form, options);
});
```

When I do

```
  {{#form-for model}}
  {{/form-for}}
```

This suggests it's a HTMLBars issue: https://github.com/ef4/liquid-fire/issues/113

**Comment by sir-dunxalot** [comment]
Hi Tom,

Thanks for opening the issue. This addon doesn't map easy form's capabilities 1-to-1. `{{#form-for}}` has been replaced by the `{{#form-wrapper}}` component. The reasoning for this was the unnecessary layer `{{form-for}}` adds to forms and the ease at which one can just do `{{input someModel.property}}. Thus, I didn't update the`form-for` helper.

I'd be open to a conversation about the benefits of adding it back but we'd have to figure out the role of `form-wrapper` vs `form-for` and all that.

What are the typical use cases you use the `model` argument of `form-for` for?

**Comment by tspacek** [comment]
Thanks, on further thought I didn't need form-for in a lot of cases, and
form-wrapper works where I do.

**Comment by sir-dunxalot** [comment]
Ok, sounds good. Well if you change your mind feel free to reopen the issue and we can discuss further.
